//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTicketera
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id_Ticket { get; set; }
        public string Nro_Ticket { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> Id_Caja { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
